/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as CheckpointsIndexRouteImport } from './routes/checkpoints/index'
import { Route as CheckpointsIdRouteImport } from './routes/checkpoints/$id'
import { Route as CheckpointsCreateRouteImport } from './routes/checkpoints/create'
import { Route as CheckpointsImportRouteImport } from './routes/checkpoints/import'
import { Route as ScoresCheckpointIdRouteImport } from './routes/scores/$checkpointId'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsIdRouteImport } from './routes/teams/$id'
import { Route as TeamsCreateRouteImport } from './routes/teams/create'
import { Route as TeamsImportRouteImport } from './routes/teams/import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointsIndexRoute = CheckpointsIndexRouteImport.update({
  id: '/checkpoints/',
  path: '/checkpoints/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointsIdRoute = CheckpointsIdRouteImport.update({
  id: '/checkpoints/$id',
  path: '/checkpoints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointsCreateRoute = CheckpointsCreateRouteImport.update({
  id: '/checkpoints/create',
  path: '/checkpoints/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointsImportRoute = CheckpointsImportRouteImport.update({
  id: '/checkpoints/import',
  path: '/checkpoints/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresCheckpointIdRoute = ScoresCheckpointIdRouteImport.update({
  id: '/scores/$checkpointId',
  path: '/scores/$checkpointId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsCreateRoute = TeamsCreateRouteImport.update({
  id: '/teams/create',
  path: '/teams/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsImportRoute = TeamsImportRouteImport.update({
  id: '/teams/import',
  path: '/teams/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/checkpoints/$id': typeof CheckpointsIdRoute
  '/checkpoints/create': typeof CheckpointsCreateRoute
  '/checkpoints/import': typeof CheckpointsImportRoute
  '/scores/$checkpointId': typeof ScoresCheckpointIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/teams/create': typeof TeamsCreateRoute
  '/teams/import': typeof TeamsImportRoute
  '/checkpoints/': typeof CheckpointsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/checkpoints/$id': typeof CheckpointsIdRoute
  '/checkpoints/create': typeof CheckpointsCreateRoute
  '/checkpoints/import': typeof CheckpointsImportRoute
  '/scores/$checkpointId': typeof ScoresCheckpointIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/teams/create': typeof TeamsCreateRoute
  '/teams/import': typeof TeamsImportRoute
  '/checkpoints': typeof CheckpointsIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/checkpoints/$id': typeof CheckpointsIdRoute
  '/checkpoints/create': typeof CheckpointsCreateRoute
  '/checkpoints/import': typeof CheckpointsImportRoute
  '/scores/$checkpointId': typeof ScoresCheckpointIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/teams/create': typeof TeamsCreateRoute
  '/teams/import': typeof TeamsImportRoute
  '/checkpoints/': typeof CheckpointsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth/login'
    | '/checkpoints/$id'
    | '/checkpoints/create'
    | '/checkpoints/import'
    | '/scores/$checkpointId'
    | '/teams/$id'
    | '/teams/create'
    | '/teams/import'
    | '/checkpoints/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth/login'
    | '/checkpoints/$id'
    | '/checkpoints/create'
    | '/checkpoints/import'
    | '/scores/$checkpointId'
    | '/teams/$id'
    | '/teams/create'
    | '/teams/import'
    | '/checkpoints'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth/login'
    | '/checkpoints/$id'
    | '/checkpoints/create'
    | '/checkpoints/import'
    | '/scores/$checkpointId'
    | '/teams/$id'
    | '/teams/create'
    | '/teams/import'
    | '/checkpoints/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthLoginRoute: typeof AuthLoginRoute
  CheckpointsIdRoute: typeof CheckpointsIdRoute
  CheckpointsCreateRoute: typeof CheckpointsCreateRoute
  CheckpointsImportRoute: typeof CheckpointsImportRoute
  ScoresCheckpointIdRoute: typeof ScoresCheckpointIdRoute
  TeamsIdRoute: typeof TeamsIdRoute
  TeamsCreateRoute: typeof TeamsCreateRoute
  TeamsImportRoute: typeof TeamsImportRoute
  CheckpointsIndexRoute: typeof CheckpointsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoints/': {
      id: '/checkpoints/'
      path: '/checkpoints'
      fullPath: '/checkpoints/'
      preLoaderRoute: typeof CheckpointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoints/$id': {
      id: '/checkpoints/$id'
      path: '/checkpoints/$id'
      fullPath: '/checkpoints/$id'
      preLoaderRoute: typeof CheckpointsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoints/create': {
      id: '/checkpoints/create'
      path: '/checkpoints/create'
      fullPath: '/checkpoints/create'
      preLoaderRoute: typeof CheckpointsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoints/import': {
      id: '/checkpoints/import'
      path: '/checkpoints/import'
      fullPath: '/checkpoints/import'
      preLoaderRoute: typeof CheckpointsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/$checkpointId': {
      id: '/scores/$checkpointId'
      path: '/scores/$checkpointId'
      fullPath: '/scores/$checkpointId'
      preLoaderRoute: typeof ScoresCheckpointIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/create': {
      id: '/teams/create'
      path: '/teams/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof TeamsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/import': {
      id: '/teams/import'
      path: '/teams/import'
      fullPath: '/teams/import'
      preLoaderRoute: typeof TeamsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthLoginRoute: AuthLoginRoute,
  CheckpointsIdRoute: CheckpointsIdRoute,
  CheckpointsCreateRoute: CheckpointsCreateRoute,
  CheckpointsImportRoute: CheckpointsImportRoute,
  ScoresCheckpointIdRoute: ScoresCheckpointIdRoute,
  TeamsIdRoute: TeamsIdRoute,
  TeamsCreateRoute: TeamsCreateRoute,
  TeamsImportRoute: TeamsImportRoute,
  CheckpointsIndexRoute: CheckpointsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
