services:
  web-dev:
    build:
      context: ./server
    container_name: web-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    profiles:
      - dev

  frontend-dev:
    build:
      context: ./client
      target: dev
    container_name: client-dev
    ports:
      - "3007:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - web-dev
    profiles:
      - dev
    stdin_open: true
    tty: true

  web-prod:
    build:
      context: ./server
    container_name: web-prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    profiles:
      - prod

  frontend-prod:
    build:
      context: ./client
    container_name: client-prod
    ports:
      - "3007:80"
    depends_on:
      - web-prod
    profiles:
      - prod

  db:
    image: postgres:17
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

