/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminCheckpoint,
  AdminTeam,
  BodyLoginAuthLoginPost,
  CreateAdventure,
  CreateCheckpoint,
  CreateTeam,
  CreateUser,
  FetchUserUsersUserIdGetParams,
  HTTPValidationError,
  LinkedAdventure,
  ListUsersUsersGetParams,
  ModifyAdventure,
  ModifyCheckpoint,
  ModifyTeam,
  PublicAdventure,
  PublicCheckpoint,
  PublicTeam,
  PublicUser,
  Token,
  UpdateUser
} from './model';

import { customInstance } from './axios';




/**
 * @summary List Users
 */
export const listUsersUsersGet = (
    params?: ListUsersUsersGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicUser[]>(
      {url: `/users/`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getListUsersUsersGetQueryKey = (params?: ListUsersUsersGetParams,) => {
    return [`/users/`, ...(params ? [params]: [])] as const;
    }

    
export const getListUsersUsersGetQueryOptions = <TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(params?: ListUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersUsersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsersUsersGet>>> = ({ signal }) => listUsersUsersGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersUsersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listUsersUsersGet>>>
export type ListUsersUsersGetQueryError = HTTPValidationError


export function useListUsersUsersGet<TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(
 params: undefined |  ListUsersUsersGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof listUsersUsersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsersUsersGet<TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(
 params?: ListUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof listUsersUsersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsersUsersGet<TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(
 params?: ListUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Users
 */

export function useListUsersUsersGet<TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(
 params?: ListUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsersUsersGetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create User
 */
export const createUserUsersPost = (
    createUser: CreateUser,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicUser>(
      {url: `/users/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUser, signal
    },
      );
    }
  


export const getCreateUserUsersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserUsersPost>>, TError,{data: CreateUser}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createUserUsersPost>>, TError,{data: CreateUser}, TContext> => {

const mutationKey = ['createUserUsersPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUserUsersPost>>, {data: CreateUser}> = (props) => {
          const {data} = props ?? {};

          return  createUserUsersPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserUsersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createUserUsersPost>>>
    export type CreateUserUsersPostMutationBody = CreateUser
    export type CreateUserUsersPostMutationError = HTTPValidationError

    /**
 * @summary Create User
 */
export const useCreateUserUsersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserUsersPost>>, TError,{data: CreateUser}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUserUsersPost>>,
        TError,
        {data: CreateUser},
        TContext
      > => {

      const mutationOptions = getCreateUserUsersPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Fetch User
 */
export const fetchUserUsersUserIdGet = (
    userId: number,
    params?: FetchUserUsersUserIdGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicUser>(
      {url: `/users/${userId}`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchUserUsersUserIdGetQueryKey = (userId: number,
    params?: FetchUserUsersUserIdGetParams,) => {
    return [`/users/${userId}`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchUserUsersUserIdGetQueryOptions = <TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(userId: number,
    params?: FetchUserUsersUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchUserUsersUserIdGetQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>> = ({ signal }) => fetchUserUsersUserIdGet(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchUserUsersUserIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>>
export type FetchUserUsersUserIdGetQueryError = HTTPValidationError


export function useFetchUserUsersUserIdGet<TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(
 userId: number,
    params: undefined |  FetchUserUsersUserIdGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchUserUsersUserIdGet<TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(
 userId: number,
    params?: FetchUserUsersUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchUserUsersUserIdGet<TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(
 userId: number,
    params?: FetchUserUsersUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch User
 */

export function useFetchUserUsersUserIdGet<TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(
 userId: number,
    params?: FetchUserUsersUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchUserUsersUserIdGetQueryOptions(userId,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update User
 */
export const updateUserUsersUserIdPatch = (
    userId: number,
    updateUser: UpdateUser,
 ) => {
      
      
      return customInstance<PublicUser>(
      {url: `/users/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUser
    },
      );
    }
  


export const getUpdateUserUsersUserIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>, TError,{userId: number;data: UpdateUser}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>, TError,{userId: number;data: UpdateUser}, TContext> => {

const mutationKey = ['updateUserUsersUserIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>, {userId: number;data: UpdateUser}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateUserUsersUserIdPatch(userId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserUsersUserIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>>
    export type UpdateUserUsersUserIdPatchMutationBody = UpdateUser
    export type UpdateUserUsersUserIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update User
 */
export const useUpdateUserUsersUserIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>, TError,{userId: number;data: UpdateUser}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>,
        TError,
        {userId: number;data: UpdateUser},
        TContext
      > => {

      const mutationOptions = getUpdateUserUsersUserIdPatchMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Delete User
 */
export const deleteUserUsersUserIdDelete = (
    userId: number,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/users/${userId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteUserUsersUserIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>, TError,{userId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>, TError,{userId: number}, TContext> => {

const mutationKey = ['deleteUserUsersUserIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  deleteUserUsersUserIdDelete(userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserUsersUserIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>>
    
    export type DeleteUserUsersUserIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete User
 */
export const useDeleteUserUsersUserIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>, TError,{userId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>,
        TError,
        {userId: number},
        TContext
      > => {

      const mutationOptions = getDeleteUserUsersUserIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Login
 */
export const loginAuthLoginPost = (
    bodyLoginAuthLoginPost: BodyLoginAuthLoginPost,
 signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
if(bodyLoginAuthLoginPost.grant_type !== undefined && bodyLoginAuthLoginPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginAuthLoginPost.grant_type)
 }
formUrlEncoded.append(`username`, bodyLoginAuthLoginPost.username)
formUrlEncoded.append(`password`, bodyLoginAuthLoginPost.password)
if(bodyLoginAuthLoginPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginAuthLoginPost.scope)
 }
if(bodyLoginAuthLoginPost.client_id !== undefined && bodyLoginAuthLoginPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginAuthLoginPost.client_id)
 }
if(bodyLoginAuthLoginPost.client_secret !== undefined && bodyLoginAuthLoginPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginAuthLoginPost.client_secret)
 }

      return customInstance<Token>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      );
    }
  


export const getLoginAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: BodyLoginAuthLoginPost}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: BodyLoginAuthLoginPost}, TContext> => {

const mutationKey = ['loginAuthLoginPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginAuthLoginPost>>, {data: BodyLoginAuthLoginPost}> = (props) => {
          const {data} = props ?? {};

          return  loginAuthLoginPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginAuthLoginPost>>>
    export type LoginAuthLoginPostMutationBody = BodyLoginAuthLoginPost
    export type LoginAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: BodyLoginAuthLoginPost}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginAuthLoginPost>>,
        TError,
        {data: BodyLoginAuthLoginPost},
        TContext
      > => {

      const mutationOptions = getLoginAuthLoginPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary List Adventures
 */
export const listAdventuresAdventuresGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<LinkedAdventure[]>(
      {url: `/adventures/`, method: 'GET', signal
    },
      );
    }
  

export const getListAdventuresAdventuresGetQueryKey = () => {
    return [`/adventures/`] as const;
    }

    
export const getListAdventuresAdventuresGetQueryOptions = <TData = Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdventuresAdventuresGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdventuresAdventuresGet>>> = ({ signal }) => listAdventuresAdventuresGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdventuresAdventuresGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAdventuresAdventuresGet>>>
export type ListAdventuresAdventuresGetQueryError = unknown


export function useListAdventuresAdventuresGet<TData = Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdventuresAdventuresGet>>,
          TError,
          Awaited<ReturnType<typeof listAdventuresAdventuresGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdventuresAdventuresGet<TData = Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdventuresAdventuresGet>>,
          TError,
          Awaited<ReturnType<typeof listAdventuresAdventuresGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdventuresAdventuresGet<TData = Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Adventures
 */

export function useListAdventuresAdventuresGet<TData = Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdventuresAdventuresGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdventuresAdventuresGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Adventure
 */
export const createAdventureAdventuresPost = (
    createAdventure: CreateAdventure,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicAdventure>(
      {url: `/adventures/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAdventure, signal
    },
      );
    }
  


export const getCreateAdventureAdventuresPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdventureAdventuresPost>>, TError,{data: CreateAdventure}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createAdventureAdventuresPost>>, TError,{data: CreateAdventure}, TContext> => {

const mutationKey = ['createAdventureAdventuresPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdventureAdventuresPost>>, {data: CreateAdventure}> = (props) => {
          const {data} = props ?? {};

          return  createAdventureAdventuresPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAdventureAdventuresPostMutationResult = NonNullable<Awaited<ReturnType<typeof createAdventureAdventuresPost>>>
    export type CreateAdventureAdventuresPostMutationBody = CreateAdventure
    export type CreateAdventureAdventuresPostMutationError = HTTPValidationError

    /**
 * @summary Create Adventure
 */
export const useCreateAdventureAdventuresPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdventureAdventuresPost>>, TError,{data: CreateAdventure}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAdventureAdventuresPost>>,
        TError,
        {data: CreateAdventure},
        TContext
      > => {

      const mutationOptions = getCreateAdventureAdventuresPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Fetch Adventure
 */
export const fetchAdventureAdventuresAdventureIdGet = (
    adventureId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicAdventure>(
      {url: `/adventures/${adventureId}`, method: 'GET', signal
    },
      );
    }
  

export const getFetchAdventureAdventuresAdventureIdGetQueryKey = (adventureId: number,) => {
    return [`/adventures/${adventureId}`] as const;
    }

    
export const getFetchAdventureAdventuresAdventureIdGetQueryOptions = <TData = Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError = HTTPValidationError>(adventureId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchAdventureAdventuresAdventureIdGetQueryKey(adventureId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>> = ({ signal }) => fetchAdventureAdventuresAdventureIdGet(adventureId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(adventureId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchAdventureAdventuresAdventureIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>>
export type FetchAdventureAdventuresAdventureIdGetQueryError = HTTPValidationError


export function useFetchAdventureAdventuresAdventureIdGet<TData = Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError = HTTPValidationError>(
 adventureId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAdventureAdventuresAdventureIdGet<TData = Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError = HTTPValidationError>(
 adventureId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAdventureAdventuresAdventureIdGet<TData = Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError = HTTPValidationError>(
 adventureId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Adventure
 */

export function useFetchAdventureAdventuresAdventureIdGet<TData = Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError = HTTPValidationError>(
 adventureId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdventureAdventuresAdventureIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchAdventureAdventuresAdventureIdGetQueryOptions(adventureId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Adventure
 */
export const updateAdventureAdventuresAdventureIdPatch = (
    adventureId: number,
    modifyAdventure: ModifyAdventure,
 ) => {
      
      
      return customInstance<PublicAdventure>(
      {url: `/adventures/${adventureId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: modifyAdventure
    },
      );
    }
  


export const getUpdateAdventureAdventuresAdventureIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdventureAdventuresAdventureIdPatch>>, TError,{adventureId: number;data: ModifyAdventure}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateAdventureAdventuresAdventureIdPatch>>, TError,{adventureId: number;data: ModifyAdventure}, TContext> => {

const mutationKey = ['updateAdventureAdventuresAdventureIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdventureAdventuresAdventureIdPatch>>, {adventureId: number;data: ModifyAdventure}> = (props) => {
          const {adventureId,data} = props ?? {};

          return  updateAdventureAdventuresAdventureIdPatch(adventureId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdventureAdventuresAdventureIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdventureAdventuresAdventureIdPatch>>>
    export type UpdateAdventureAdventuresAdventureIdPatchMutationBody = ModifyAdventure
    export type UpdateAdventureAdventuresAdventureIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Adventure
 */
export const useUpdateAdventureAdventuresAdventureIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdventureAdventuresAdventureIdPatch>>, TError,{adventureId: number;data: ModifyAdventure}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdventureAdventuresAdventureIdPatch>>,
        TError,
        {adventureId: number;data: ModifyAdventure},
        TContext
      > => {

      const mutationOptions = getUpdateAdventureAdventuresAdventureIdPatchMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Delete Adventure
 */
export const deleteAdventureAdventuresAdventureIdDelete = (
    adventureId: number,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/adventures/${adventureId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteAdventureAdventuresAdventureIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdventureAdventuresAdventureIdDelete>>, TError,{adventureId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdventureAdventuresAdventureIdDelete>>, TError,{adventureId: number}, TContext> => {

const mutationKey = ['deleteAdventureAdventuresAdventureIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdventureAdventuresAdventureIdDelete>>, {adventureId: number}> = (props) => {
          const {adventureId} = props ?? {};

          return  deleteAdventureAdventuresAdventureIdDelete(adventureId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdventureAdventuresAdventureIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdventureAdventuresAdventureIdDelete>>>
    
    export type DeleteAdventureAdventuresAdventureIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Adventure
 */
export const useDeleteAdventureAdventuresAdventureIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdventureAdventuresAdventureIdDelete>>, TError,{adventureId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdventureAdventuresAdventureIdDelete>>,
        TError,
        {adventureId: number},
        TContext
      > => {

      const mutationOptions = getDeleteAdventureAdventuresAdventureIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary List Checkpoints
 */
export const listCheckpointsCheckpointsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicCheckpoint[]>(
      {url: `/checkpoints/`, method: 'GET', signal
    },
      );
    }
  

export const getListCheckpointsCheckpointsGetQueryKey = () => {
    return [`/checkpoints/`] as const;
    }

    
export const getListCheckpointsCheckpointsGetQueryOptions = <TData = Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCheckpointsCheckpointsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>> = ({ signal }) => listCheckpointsCheckpointsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCheckpointsCheckpointsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>>
export type ListCheckpointsCheckpointsGetQueryError = unknown


export function useListCheckpointsCheckpointsGet<TData = Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>,
          TError,
          Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCheckpointsCheckpointsGet<TData = Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>,
          TError,
          Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCheckpointsCheckpointsGet<TData = Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Checkpoints
 */

export function useListCheckpointsCheckpointsGet<TData = Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCheckpointsCheckpointsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCheckpointsCheckpointsGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Checkpoint
 */
export const createCheckpointCheckpointsPost = (
    createCheckpoint: CreateCheckpoint,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicCheckpoint>(
      {url: `/checkpoints/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCheckpoint, signal
    },
      );
    }
  


export const getCreateCheckpointCheckpointsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckpointCheckpointsPost>>, TError,{data: CreateCheckpoint}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCheckpointCheckpointsPost>>, TError,{data: CreateCheckpoint}, TContext> => {

const mutationKey = ['createCheckpointCheckpointsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCheckpointCheckpointsPost>>, {data: CreateCheckpoint}> = (props) => {
          const {data} = props ?? {};

          return  createCheckpointCheckpointsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCheckpointCheckpointsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCheckpointCheckpointsPost>>>
    export type CreateCheckpointCheckpointsPostMutationBody = CreateCheckpoint
    export type CreateCheckpointCheckpointsPostMutationError = HTTPValidationError

    /**
 * @summary Create Checkpoint
 */
export const useCreateCheckpointCheckpointsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckpointCheckpointsPost>>, TError,{data: CreateCheckpoint}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCheckpointCheckpointsPost>>,
        TError,
        {data: CreateCheckpoint},
        TContext
      > => {

      const mutationOptions = getCreateCheckpointCheckpointsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Fetch Checkpoint
 */
export const fetchCheckpointCheckpointsCheckpointIdGet = (
    checkpointId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicCheckpoint>(
      {url: `/checkpoints/${checkpointId}`, method: 'GET', signal
    },
      );
    }
  

export const getFetchCheckpointCheckpointsCheckpointIdGetQueryKey = (checkpointId: number,) => {
    return [`/checkpoints/${checkpointId}`] as const;
    }

    
export const getFetchCheckpointCheckpointsCheckpointIdGetQueryOptions = <TData = Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError = HTTPValidationError>(checkpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchCheckpointCheckpointsCheckpointIdGetQueryKey(checkpointId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>> = ({ signal }) => fetchCheckpointCheckpointsCheckpointIdGet(checkpointId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(checkpointId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchCheckpointCheckpointsCheckpointIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>>
export type FetchCheckpointCheckpointsCheckpointIdGetQueryError = HTTPValidationError


export function useFetchCheckpointCheckpointsCheckpointIdGet<TData = Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError = HTTPValidationError>(
 checkpointId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchCheckpointCheckpointsCheckpointIdGet<TData = Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError = HTTPValidationError>(
 checkpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchCheckpointCheckpointsCheckpointIdGet<TData = Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError = HTTPValidationError>(
 checkpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Checkpoint
 */

export function useFetchCheckpointCheckpointsCheckpointIdGet<TData = Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError = HTTPValidationError>(
 checkpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchCheckpointCheckpointsCheckpointIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchCheckpointCheckpointsCheckpointIdGetQueryOptions(checkpointId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Checkpoint
 */
export const updateCheckpointCheckpointsCheckpointIdPatch = (
    checkpointId: number,
    modifyCheckpoint: ModifyCheckpoint,
 ) => {
      
      
      return customInstance<PublicCheckpoint>(
      {url: `/checkpoints/${checkpointId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: modifyCheckpoint
    },
      );
    }
  


export const getUpdateCheckpointCheckpointsCheckpointIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCheckpointCheckpointsCheckpointIdPatch>>, TError,{checkpointId: number;data: ModifyCheckpoint}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateCheckpointCheckpointsCheckpointIdPatch>>, TError,{checkpointId: number;data: ModifyCheckpoint}, TContext> => {

const mutationKey = ['updateCheckpointCheckpointsCheckpointIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCheckpointCheckpointsCheckpointIdPatch>>, {checkpointId: number;data: ModifyCheckpoint}> = (props) => {
          const {checkpointId,data} = props ?? {};

          return  updateCheckpointCheckpointsCheckpointIdPatch(checkpointId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCheckpointCheckpointsCheckpointIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateCheckpointCheckpointsCheckpointIdPatch>>>
    export type UpdateCheckpointCheckpointsCheckpointIdPatchMutationBody = ModifyCheckpoint
    export type UpdateCheckpointCheckpointsCheckpointIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Checkpoint
 */
export const useUpdateCheckpointCheckpointsCheckpointIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCheckpointCheckpointsCheckpointIdPatch>>, TError,{checkpointId: number;data: ModifyCheckpoint}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCheckpointCheckpointsCheckpointIdPatch>>,
        TError,
        {checkpointId: number;data: ModifyCheckpoint},
        TContext
      > => {

      const mutationOptions = getUpdateCheckpointCheckpointsCheckpointIdPatchMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Delete Checkpoint
 */
export const deleteCheckpointCheckpointsCheckpointIdDelete = (
    checkpointId: number,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/checkpoints/${checkpointId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteCheckpointCheckpointsCheckpointIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCheckpointCheckpointsCheckpointIdDelete>>, TError,{checkpointId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCheckpointCheckpointsCheckpointIdDelete>>, TError,{checkpointId: number}, TContext> => {

const mutationKey = ['deleteCheckpointCheckpointsCheckpointIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCheckpointCheckpointsCheckpointIdDelete>>, {checkpointId: number}> = (props) => {
          const {checkpointId} = props ?? {};

          return  deleteCheckpointCheckpointsCheckpointIdDelete(checkpointId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCheckpointCheckpointsCheckpointIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCheckpointCheckpointsCheckpointIdDelete>>>
    
    export type DeleteCheckpointCheckpointsCheckpointIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Checkpoint
 */
export const useDeleteCheckpointCheckpointsCheckpointIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCheckpointCheckpointsCheckpointIdDelete>>, TError,{checkpointId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCheckpointCheckpointsCheckpointIdDelete>>,
        TError,
        {checkpointId: number},
        TContext
      > => {

      const mutationOptions = getDeleteCheckpointCheckpointsCheckpointIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary List Admin Checkpoints
 */
export const listAdminCheckpointsCheckpointsAdminGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminCheckpoint[]>(
      {url: `/checkpoints/admin/`, method: 'GET', signal
    },
      );
    }
  

export const getListAdminCheckpointsCheckpointsAdminGetQueryKey = () => {
    return [`/checkpoints/admin/`] as const;
    }

    
export const getListAdminCheckpointsCheckpointsAdminGetQueryOptions = <TData = Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminCheckpointsCheckpointsAdminGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>> = ({ signal }) => listAdminCheckpointsCheckpointsAdminGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminCheckpointsCheckpointsAdminGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>>
export type ListAdminCheckpointsCheckpointsAdminGetQueryError = unknown


export function useListAdminCheckpointsCheckpointsAdminGet<TData = Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>,
          TError,
          Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminCheckpointsCheckpointsAdminGet<TData = Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>,
          TError,
          Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminCheckpointsCheckpointsAdminGet<TData = Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Admin Checkpoints
 */

export function useListAdminCheckpointsCheckpointsAdminGet<TData = Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCheckpointsCheckpointsAdminGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminCheckpointsCheckpointsAdminGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Fetch Admin Checkpoint
 */
export const fetchAdminCheckpointCheckpointsAdminCheckpointIdGet = (
    checkpointId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminCheckpoint>(
      {url: `/checkpoints/admin/${checkpointId}`, method: 'GET', signal
    },
      );
    }
  

export const getFetchAdminCheckpointCheckpointsAdminCheckpointIdGetQueryKey = (checkpointId: number,) => {
    return [`/checkpoints/admin/${checkpointId}`] as const;
    }

    
export const getFetchAdminCheckpointCheckpointsAdminCheckpointIdGetQueryOptions = <TData = Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError = HTTPValidationError>(checkpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchAdminCheckpointCheckpointsAdminCheckpointIdGetQueryKey(checkpointId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>> = ({ signal }) => fetchAdminCheckpointCheckpointsAdminCheckpointIdGet(checkpointId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(checkpointId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchAdminCheckpointCheckpointsAdminCheckpointIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>>
export type FetchAdminCheckpointCheckpointsAdminCheckpointIdGetQueryError = HTTPValidationError


export function useFetchAdminCheckpointCheckpointsAdminCheckpointIdGet<TData = Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError = HTTPValidationError>(
 checkpointId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAdminCheckpointCheckpointsAdminCheckpointIdGet<TData = Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError = HTTPValidationError>(
 checkpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAdminCheckpointCheckpointsAdminCheckpointIdGet<TData = Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError = HTTPValidationError>(
 checkpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Admin Checkpoint
 */

export function useFetchAdminCheckpointCheckpointsAdminCheckpointIdGet<TData = Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError = HTTPValidationError>(
 checkpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminCheckpointCheckpointsAdminCheckpointIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchAdminCheckpointCheckpointsAdminCheckpointIdGetQueryOptions(checkpointId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List Teams
 */
export const listTeamsTeamsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicTeam[]>(
      {url: `/teams/`, method: 'GET', signal
    },
      );
    }
  

export const getListTeamsTeamsGetQueryKey = () => {
    return [`/teams/`] as const;
    }

    
export const getListTeamsTeamsGetQueryOptions = <TData = Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamsTeamsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTeamsTeamsGet>>> = ({ signal }) => listTeamsTeamsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTeamsTeamsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTeamsTeamsGet>>>
export type ListTeamsTeamsGetQueryError = unknown


export function useListTeamsTeamsGet<TData = Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTeamsTeamsGet>>,
          TError,
          Awaited<ReturnType<typeof listTeamsTeamsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamsTeamsGet<TData = Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTeamsTeamsGet>>,
          TError,
          Awaited<ReturnType<typeof listTeamsTeamsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamsTeamsGet<TData = Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Teams
 */

export function useListTeamsTeamsGet<TData = Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsTeamsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTeamsTeamsGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Team
 */
export const createTeamTeamsPost = (
    createTeam: CreateTeam,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicTeam>(
      {url: `/teams/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTeam, signal
    },
      );
    }
  


export const getCreateTeamTeamsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeamTeamsPost>>, TError,{data: CreateTeam}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTeamTeamsPost>>, TError,{data: CreateTeam}, TContext> => {

const mutationKey = ['createTeamTeamsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTeamTeamsPost>>, {data: CreateTeam}> = (props) => {
          const {data} = props ?? {};

          return  createTeamTeamsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTeamTeamsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTeamTeamsPost>>>
    export type CreateTeamTeamsPostMutationBody = CreateTeam
    export type CreateTeamTeamsPostMutationError = HTTPValidationError

    /**
 * @summary Create Team
 */
export const useCreateTeamTeamsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeamTeamsPost>>, TError,{data: CreateTeam}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTeamTeamsPost>>,
        TError,
        {data: CreateTeam},
        TContext
      > => {

      const mutationOptions = getCreateTeamTeamsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Fetch Team
 */
export const fetchTeamTeamsTeamIdGet = (
    teamId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicTeam>(
      {url: `/teams/${teamId}`, method: 'GET', signal
    },
      );
    }
  

export const getFetchTeamTeamsTeamIdGetQueryKey = (teamId: number,) => {
    return [`/teams/${teamId}`] as const;
    }

    
export const getFetchTeamTeamsTeamIdGetQueryOptions = <TData = Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError = HTTPValidationError>(teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchTeamTeamsTeamIdGetQueryKey(teamId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>> = ({ signal }) => fetchTeamTeamsTeamIdGet(teamId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchTeamTeamsTeamIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>>
export type FetchTeamTeamsTeamIdGetQueryError = HTTPValidationError


export function useFetchTeamTeamsTeamIdGet<TData = Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError = HTTPValidationError>(
 teamId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchTeamTeamsTeamIdGet<TData = Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError = HTTPValidationError>(
 teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchTeamTeamsTeamIdGet<TData = Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError = HTTPValidationError>(
 teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Team
 */

export function useFetchTeamTeamsTeamIdGet<TData = Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError = HTTPValidationError>(
 teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTeamTeamsTeamIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchTeamTeamsTeamIdGetQueryOptions(teamId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Team
 */
export const updateTeamTeamsTeamIdPatch = (
    teamId: number,
    modifyTeam: ModifyTeam,
 ) => {
      
      
      return customInstance<PublicTeam>(
      {url: `/teams/${teamId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: modifyTeam
    },
      );
    }
  


export const getUpdateTeamTeamsTeamIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeamTeamsTeamIdPatch>>, TError,{teamId: number;data: ModifyTeam}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTeamTeamsTeamIdPatch>>, TError,{teamId: number;data: ModifyTeam}, TContext> => {

const mutationKey = ['updateTeamTeamsTeamIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTeamTeamsTeamIdPatch>>, {teamId: number;data: ModifyTeam}> = (props) => {
          const {teamId,data} = props ?? {};

          return  updateTeamTeamsTeamIdPatch(teamId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTeamTeamsTeamIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateTeamTeamsTeamIdPatch>>>
    export type UpdateTeamTeamsTeamIdPatchMutationBody = ModifyTeam
    export type UpdateTeamTeamsTeamIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Team
 */
export const useUpdateTeamTeamsTeamIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeamTeamsTeamIdPatch>>, TError,{teamId: number;data: ModifyTeam}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTeamTeamsTeamIdPatch>>,
        TError,
        {teamId: number;data: ModifyTeam},
        TContext
      > => {

      const mutationOptions = getUpdateTeamTeamsTeamIdPatchMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Delete Team
 */
export const deleteTeamTeamsTeamIdDelete = (
    teamId: number,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/teams/${teamId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteTeamTeamsTeamIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTeamTeamsTeamIdDelete>>, TError,{teamId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTeamTeamsTeamIdDelete>>, TError,{teamId: number}, TContext> => {

const mutationKey = ['deleteTeamTeamsTeamIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTeamTeamsTeamIdDelete>>, {teamId: number}> = (props) => {
          const {teamId} = props ?? {};

          return  deleteTeamTeamsTeamIdDelete(teamId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTeamTeamsTeamIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTeamTeamsTeamIdDelete>>>
    
    export type DeleteTeamTeamsTeamIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Team
 */
export const useDeleteTeamTeamsTeamIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTeamTeamsTeamIdDelete>>, TError,{teamId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTeamTeamsTeamIdDelete>>,
        TError,
        {teamId: number},
        TContext
      > => {

      const mutationOptions = getDeleteTeamTeamsTeamIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary List Admin Teams
 */
export const listAdminTeamsTeamsAdminGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminTeam[]>(
      {url: `/teams/admin/`, method: 'GET', signal
    },
      );
    }
  

export const getListAdminTeamsTeamsAdminGetQueryKey = () => {
    return [`/teams/admin/`] as const;
    }

    
export const getListAdminTeamsTeamsAdminGetQueryOptions = <TData = Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminTeamsTeamsAdminGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>> = ({ signal }) => listAdminTeamsTeamsAdminGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminTeamsTeamsAdminGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>>
export type ListAdminTeamsTeamsAdminGetQueryError = unknown


export function useListAdminTeamsTeamsAdminGet<TData = Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>,
          TError,
          Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminTeamsTeamsAdminGet<TData = Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>,
          TError,
          Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminTeamsTeamsAdminGet<TData = Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Admin Teams
 */

export function useListAdminTeamsTeamsAdminGet<TData = Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTeamsTeamsAdminGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminTeamsTeamsAdminGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Fetch Admin Team
 */
export const fetchAdminTeamTeamsAdminTeamIdGet = (
    teamId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminTeam>(
      {url: `/teams/admin/${teamId}`, method: 'GET', signal
    },
      );
    }
  

export const getFetchAdminTeamTeamsAdminTeamIdGetQueryKey = (teamId: number,) => {
    return [`/teams/admin/${teamId}`] as const;
    }

    
export const getFetchAdminTeamTeamsAdminTeamIdGetQueryOptions = <TData = Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError = HTTPValidationError>(teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchAdminTeamTeamsAdminTeamIdGetQueryKey(teamId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>> = ({ signal }) => fetchAdminTeamTeamsAdminTeamIdGet(teamId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchAdminTeamTeamsAdminTeamIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>>
export type FetchAdminTeamTeamsAdminTeamIdGetQueryError = HTTPValidationError


export function useFetchAdminTeamTeamsAdminTeamIdGet<TData = Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError = HTTPValidationError>(
 teamId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAdminTeamTeamsAdminTeamIdGet<TData = Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError = HTTPValidationError>(
 teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAdminTeamTeamsAdminTeamIdGet<TData = Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError = HTTPValidationError>(
 teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Admin Team
 */

export function useFetchAdminTeamTeamsAdminTeamIdGet<TData = Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError = HTTPValidationError>(
 teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAdminTeamTeamsAdminTeamIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchAdminTeamTeamsAdminTeamIdGetQueryOptions(teamId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




