/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyLoginAuthLoginPost,
  CreateUser,
  FetchUserUsersUserIdGetParams,
  HTTPValidationError,
  ListUsersUsersGetParams,
  PublicUser,
  Token,
  UpdateUser
} from './model';

import { customInstance } from './axios';




/**
 * @summary List Users
 */
export const listUsersUsersGet = (
    params?: ListUsersUsersGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicUser[]>(
      {url: `/users/`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getListUsersUsersGetQueryKey = (params?: ListUsersUsersGetParams,) => {
    return [`/users/`, ...(params ? [params]: [])] as const;
    }

    
export const getListUsersUsersGetQueryOptions = <TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(params?: ListUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersUsersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsersUsersGet>>> = ({ signal }) => listUsersUsersGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersUsersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listUsersUsersGet>>>
export type ListUsersUsersGetQueryError = HTTPValidationError


export function useListUsersUsersGet<TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(
 params: undefined |  ListUsersUsersGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof listUsersUsersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsersUsersGet<TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(
 params?: ListUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof listUsersUsersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsersUsersGet<TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(
 params?: ListUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Users
 */

export function useListUsersUsersGet<TData = Awaited<ReturnType<typeof listUsersUsersGet>>, TError = HTTPValidationError>(
 params?: ListUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsersUsersGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsersUsersGetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create User
 */
export const createUserUsersPost = (
    createUser: CreateUser,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicUser>(
      {url: `/users/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUser, signal
    },
      );
    }
  


export const getCreateUserUsersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserUsersPost>>, TError,{data: CreateUser}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createUserUsersPost>>, TError,{data: CreateUser}, TContext> => {

const mutationKey = ['createUserUsersPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUserUsersPost>>, {data: CreateUser}> = (props) => {
          const {data} = props ?? {};

          return  createUserUsersPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserUsersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createUserUsersPost>>>
    export type CreateUserUsersPostMutationBody = CreateUser
    export type CreateUserUsersPostMutationError = HTTPValidationError

    /**
 * @summary Create User
 */
export const useCreateUserUsersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserUsersPost>>, TError,{data: CreateUser}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUserUsersPost>>,
        TError,
        {data: CreateUser},
        TContext
      > => {

      const mutationOptions = getCreateUserUsersPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Fetch User
 */
export const fetchUserUsersUserIdGet = (
    userId: number,
    params?: FetchUserUsersUserIdGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicUser>(
      {url: `/users/${userId}`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchUserUsersUserIdGetQueryKey = (userId: number,
    params?: FetchUserUsersUserIdGetParams,) => {
    return [`/users/${userId}`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchUserUsersUserIdGetQueryOptions = <TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(userId: number,
    params?: FetchUserUsersUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchUserUsersUserIdGetQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>> = ({ signal }) => fetchUserUsersUserIdGet(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchUserUsersUserIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>>
export type FetchUserUsersUserIdGetQueryError = HTTPValidationError


export function useFetchUserUsersUserIdGet<TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(
 userId: number,
    params: undefined |  FetchUserUsersUserIdGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchUserUsersUserIdGet<TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(
 userId: number,
    params?: FetchUserUsersUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchUserUsersUserIdGet<TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(
 userId: number,
    params?: FetchUserUsersUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch User
 */

export function useFetchUserUsersUserIdGet<TData = Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError = HTTPValidationError>(
 userId: number,
    params?: FetchUserUsersUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchUserUsersUserIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchUserUsersUserIdGetQueryOptions(userId,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update User
 */
export const updateUserUsersUserIdPatch = (
    userId: number,
    updateUser: UpdateUser,
 ) => {
      
      
      return customInstance<PublicUser>(
      {url: `/users/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUser
    },
      );
    }
  


export const getUpdateUserUsersUserIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>, TError,{userId: number;data: UpdateUser}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>, TError,{userId: number;data: UpdateUser}, TContext> => {

const mutationKey = ['updateUserUsersUserIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>, {userId: number;data: UpdateUser}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateUserUsersUserIdPatch(userId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserUsersUserIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>>
    export type UpdateUserUsersUserIdPatchMutationBody = UpdateUser
    export type UpdateUserUsersUserIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update User
 */
export const useUpdateUserUsersUserIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>, TError,{userId: number;data: UpdateUser}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserUsersUserIdPatch>>,
        TError,
        {userId: number;data: UpdateUser},
        TContext
      > => {

      const mutationOptions = getUpdateUserUsersUserIdPatchMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Delete User
 */
export const deleteUserUsersUserIdDelete = (
    userId: number,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/users/${userId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteUserUsersUserIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>, TError,{userId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>, TError,{userId: number}, TContext> => {

const mutationKey = ['deleteUserUsersUserIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  deleteUserUsersUserIdDelete(userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserUsersUserIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>>
    
    export type DeleteUserUsersUserIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete User
 */
export const useDeleteUserUsersUserIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>, TError,{userId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserUsersUserIdDelete>>,
        TError,
        {userId: number},
        TContext
      > => {

      const mutationOptions = getDeleteUserUsersUserIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Login
 */
export const loginAuthLoginPost = (
    bodyLoginAuthLoginPost: BodyLoginAuthLoginPost,
 signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
if(bodyLoginAuthLoginPost.grant_type !== undefined && bodyLoginAuthLoginPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginAuthLoginPost.grant_type)
 }
formUrlEncoded.append(`username`, bodyLoginAuthLoginPost.username)
formUrlEncoded.append(`password`, bodyLoginAuthLoginPost.password)
if(bodyLoginAuthLoginPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginAuthLoginPost.scope)
 }
if(bodyLoginAuthLoginPost.client_id !== undefined && bodyLoginAuthLoginPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginAuthLoginPost.client_id)
 }
if(bodyLoginAuthLoginPost.client_secret !== undefined && bodyLoginAuthLoginPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginAuthLoginPost.client_secret)
 }

      return customInstance<Token>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      );
    }
  


export const getLoginAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: BodyLoginAuthLoginPost}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: BodyLoginAuthLoginPost}, TContext> => {

const mutationKey = ['loginAuthLoginPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginAuthLoginPost>>, {data: BodyLoginAuthLoginPost}> = (props) => {
          const {data} = props ?? {};

          return  loginAuthLoginPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginAuthLoginPost>>>
    export type LoginAuthLoginPostMutationBody = BodyLoginAuthLoginPost
    export type LoginAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: BodyLoginAuthLoginPost}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginAuthLoginPost>>,
        TError,
        {data: BodyLoginAuthLoginPost},
        TContext
      > => {

      const mutationOptions = getLoginAuthLoginPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
