"""add checkpoints

Revision ID: 06ab2ae65faa
Revises: 3a175b657a89
Create Date: 2025-08-02 14:35:46.458980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "06ab2ae65faa"
down_revision: Union[str, Sequence[str], None] = "3a175b657a89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dbcheckpoint",
        sa.Column("org_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "org_abbreviation", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("longitude", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "checkpoint_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("org_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("org_link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_person", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requirements", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lanes", sa.Integer(), nullable=False),
        sa.Column("photo_permission", sa.Boolean(), nullable=False),
        sa.Column("accessible", sa.Boolean(), nullable=False),
        sa.Column("adventure_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adventure_id"],
            ["dbadventure.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dbcheckpoint")
    # ### end Alembic commands ###
