"""add numbers for checkpoints

Revision ID: 0f0aeb2c6e7a
Revises: dca4b55039fa
Create Date: 2025-08-10 05:29:53.974957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f0aeb2c6e7a"
down_revision: Union[str, Sequence[str], None] = "dca4b55039fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dbcheckpoint",
        sa.Column("number", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index(
        op.f("ix_dbcheckpoint_number"), "dbcheckpoint", ["number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dbcheckpoint_number"), table_name="dbcheckpoint")
    op.drop_column("dbcheckpoint", "number")
    # ### end Alembic commands ###
