"""ensure team numbers are unique in an adventure

Revision ID: 108412f48bde
Revises: 70b383d487eb
Create Date: 2025-09-19 08:22:23.492826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108412f48bde'
down_revision: Union[str, Sequence[str], None] = '70b383d487eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dbteam_number'), 'dbteam', ['number'], unique=False)
    op.create_unique_constraint('uq_team_adventure_number', 'dbteam', ['adventure_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_adventure_number', 'dbteam', type_='unique')
    op.drop_index(op.f('ix_dbteam_number'), table_name='dbteam')
    # ### end Alembic commands ###
