"""add score toggle to adventure

Revision ID: 27aa91de3486
Revises: e68b3526cc95
Create Date: 2025-09-22 12:48:39.590772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27aa91de3486'
down_revision: Union[str, Sequence[str], None] = 'e68b3526cc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbadventure', sa.Column('can_add_scores', sa.Boolean(), nullable=True, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbadventure', 'can_add_scores')
    # ### end Alembic commands ###
