"""team numbers

Revision ID: 70b383d487eb
Revises: e48dce8759fe
Create Date: 2025-09-19 08:12:15.956080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b383d487eb'
down_revision: Union[str, Sequence[str], None] = 'e48dce8759fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbteam', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbteam', 'number')
    # ### end Alembic commands ###
