"""add player count

Revision ID: 711393a25571
Revises: 108412f48bde
Create Date: 2025-09-19 08:34:49.107087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711393a25571'
down_revision: Union[str, Sequence[str], None] = '108412f48bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbteam', sa.Column('player_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbteam', 'player_count')
    # ### end Alembic commands ###
