"""add push subscriptions

Revision ID: 78881c4930ba
Revises: 33f5e1f99a0d
Create Date: 2025-08-06 08:21:22.222937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "78881c4930ba"
down_revision: Union[str, Sequence[str], None] = "33f5e1f99a0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dbpushsubscription",
        sa.Column("endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("keys", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dbpushsubscription_endpoint"),
        "dbpushsubscription",
        ["endpoint"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dbpushsubscription_endpoint"), table_name="dbpushsubscription"
    )
    op.drop_table("dbpushsubscription")
    # ### end Alembic commands ###
