"""add created_at to scores

Revision ID: 8048581f0a2a
Revises: e042807d8f94
Create Date: 2025-08-12 06:36:21.653745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import time


# revision identifiers, used by Alembic.
revision: str = "8048581f0a2a"
down_revision: Union[str, Sequence[str], None] = "e042807d8f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dbscore",
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    op.execute(
        sa.text(
            "UPDATE dbscore SET created_at = timezone('utc', now()) WHERE created_at IS NULL"
        )
    )
    op.alter_column("dbscore", "created_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dbscore", "created_at")
    # ### end Alembic commands ###
