"""add dbappsettings singleton

Revision ID: 854ae58cdbdf
Revises: 8048581f0a2a
Create Date: 2025-09-16 08:19:02.421028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854ae58cdbdf'
down_revision: Union[str, Sequence[str], None] = '8048581f0a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbappsettings',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_adventure_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('id = 1', name='app_settings_singleton'),
    sa.ForeignKeyConstraint(['current_adventure_id'], ['dbadventure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("INSERT INTO dbappsettings (id) VALUES (1) ON CONFLICT DO NOTHING")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbappsettings')
    # ### end Alembic commands ###
