"""add areas for checkpoints

Revision ID: 9710a9ec98d6
Revises: 0f0aeb2c6e7a
Create Date: 2025-08-10 05:42:15.675202

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9710a9ec98d6"
down_revision: Union[str, Sequence[str], None] = "0f0aeb2c6e7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dbcheckpoint",
        sa.Column("area", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index(
        op.f("ix_dbcheckpoint_area"), "dbcheckpoint", ["area"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dbcheckpoint_area"), table_name="dbcheckpoint")
    op.drop_column("dbcheckpoint", "area")
    # ### end Alembic commands ###
