"""link players to teams

Revision ID: b341ae85bf71
Revises: f499189d89d9
Create Date: 2025-09-19 07:29:16.622451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b341ae85bf71'
down_revision: Union[str, Sequence[str], None] = 'f499189d89d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dbplayer_team_id_fkey'), 'dbplayer', type_='foreignkey')
    op.create_foreign_key(None, 'dbplayer', 'dbteam', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dbplayer', type_='foreignkey')
    op.create_foreign_key(op.f('dbplayer_team_id_fkey'), 'dbplayer', 'dbadventure', ['team_id'], ['id'])
    # ### end Alembic commands ###
