"""fix player count

Revision ID: c807d36dc495
Revises: 711393a25571
Create Date: 2025-09-19 08:41:33.960699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c807d36dc495'
down_revision: Union[str, Sequence[str], None] = '711393a25571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbteam', 'player_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbteam', sa.Column('player_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
