"""add language versions for news

Revision ID: d26e9aa66430
Revises: ccf22af66366
Create Date: 2025-08-06 13:19:37.451077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d26e9aa66430"
down_revision: Union[str, Sequence[str], None] = "ccf22af66366"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dbnews",
        sa.Column("title_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "dbnews",
        sa.Column("title_fi", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "dbnews",
        sa.Column("title_sv", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "dbnews",
        sa.Column("contents_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "dbnews",
        sa.Column("contents_fi", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "dbnews",
        sa.Column("contents_sv", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_column("dbnews", "title")
    op.drop_column("dbnews", "contents")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dbnews",
        sa.Column("contents", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "dbnews", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("dbnews", "contents_sv")
    op.drop_column("dbnews", "contents_fi")
    op.drop_column("dbnews", "contents_en")
    op.drop_column("dbnews", "title_sv")
    op.drop_column("dbnews", "title_fi")
    op.drop_column("dbnews", "title_en")
    # ### end Alembic commands ###
