"""add published_at for news

Revision ID: dca4b55039fa
Revises: d26e9aa66430
Create Date: 2025-08-06 15:17:14.394014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "dca4b55039fa"
down_revision: Union[str, Sequence[str], None] = "d26e9aa66430"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dbnews", sa.Column("published_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dbnews", "published_at")
    # ### end Alembic commands ###
