"""add auth fields

Revision ID: dd8737e6ad23
Revises: c14abd936d44
Create Date: 2025-07-29 08:42:46.206298

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "dd8737e6ad23"
down_revision: Union[str, Sequence[str], None] = "c14abd936d44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    role_enum = sa.Enum("guest", "user", "admin", name="role")
    role_enum.create(op.get_bind())

    op.add_column(
        "dbuser",
        sa.Column(
            "hash",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "dbuser",
        sa.Column(
            "role",
            role_enum,
            nullable=False,
            server_default="guest",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dbuser", "role")
    op.drop_column("dbuser", "hash")
    sa.Enum(name="role").drop(op.get_bind())
    # ### end Alembic commands ###
