"""add scores

Revision ID: e042807d8f94
Revises: 9710a9ec98d6
Create Date: 2025-08-11 08:14:13.286483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e042807d8f94"
down_revision: Union[str, Sequence[str], None] = "9710a9ec98d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dbscore",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("players", sa.Integer(), nullable=False),
        sa.Column("adventure_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("checkpoint_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adventure_id"],
            ["dbadventure.id"],
        ),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"],
            ["dbcheckpoint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["dbteam.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dbscore_players"), "dbscore", ["players"], unique=False)
    op.create_index(op.f("ix_dbscore_score"), "dbscore", ["score"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dbscore_score"), table_name="dbscore")
    op.drop_index(op.f("ix_dbscore_players"), table_name="dbscore")
    op.drop_table("dbscore")
    # ### end Alembic commands ###
