/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PublicAdventure } from './publicAdventure';

export interface AdminCheckpoint {
  org_name: string;
  org_abbreviation: string;
  category: string;
  latitude: string;
  longitude: string;
  address: string;
  checkpoint_description: string;
  org_description: string;
  org_link: string;
  accessible: boolean;
  id: number;
  contact_person: string;
  contact_email: string;
  contact_phone: string;
  requirements: string;
  lanes: number;
  photo_permission: boolean;
  adventure_id: number;
  adventure: PublicAdventure;
  active: boolean;
}
