/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DBAdventure } from './dBAdventure';

export interface AdminTeam {
  name: string;
  id: number;
  adventure_id: number;
  adventure: DBAdventure;
  active: boolean;
}
