/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AdminTeamNumber } from './adminTeamNumber';
import type { DBAdventure } from './dBAdventure';
import type { AdminPlayer } from './adminPlayer';
import type { AdminTeamPlayerCount } from './adminTeamPlayerCount';

export interface AdminTeam {
  name: string;
  id: number;
  number: AdminTeamNumber;
  adventure_id: number;
  adventure: DBAdventure;
  players: AdminPlayer[];
  player_count: AdminTeamPlayerCount;
  active: boolean;
}
