/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface AllocateResult {
  status: string;
  /** Amount of updated checkpoints */
  updated: number;
}
