/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface AllocateAreasResult {
  /** Amount of updated checkpoints */
  updated: number;
  /** How many clusters we ended up with */
  clusters: number;
  /** Amount of individual checkpoints */
  noise: number;
  /** Amount of areas in total */
  total_areas: number;
}
