/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CreatePlayer {
  /** Name of the player */
  name: string;
  /** Phone number of the player */
  phone: string;
  /** ID of the team the player belongs to */
  team_id: number;
}
