/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CreateNews {
  title_en: string;
  title_fi: string;
  title_sv: string;
  contents_en: string;
  contents_fi: string;
  contents_sv: string;
  active: boolean;
}
