/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreatePushSubscriptionKeys } from './createPushSubscriptionKeys';

export interface CreatePushSubscription {
  endpoint: string;
  keys: CreatePushSubscriptionKeys;
}
