/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateCheckpointLatitude } from './createCheckpointLatitude';
import type { CreateCheckpointLongitude } from './createCheckpointLongitude';

export interface CreateCheckpoint {
  org_name: string;
  org_abbreviation: string;
  contact_person: string;
  contact_email: string;
  contact_phone: string;
  category: string;
  latitude?: CreateCheckpointLatitude;
  longitude?: CreateCheckpointLongitude;
  address: string;
  requirements: string;
  lanes: number;
  checkpoint_description: string;
  org_description: string;
  org_link: string;
  photo_permission: boolean;
  accessible: boolean;
}
