/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateCheckpointNumber } from './createCheckpointNumber';
import type { CreateCheckpointArea } from './createCheckpointArea';
import type { CreateCheckpointOrgName } from './createCheckpointOrgName';
import type { CreateCheckpointOrgAbbreviation } from './createCheckpointOrgAbbreviation';
import type { CreateCheckpointContactPerson } from './createCheckpointContactPerson';
import type { CreateCheckpointContactEmail } from './createCheckpointContactEmail';
import type { CreateCheckpointContactPhone } from './createCheckpointContactPhone';
import type { CreateCheckpointCategory } from './createCheckpointCategory';
import type { CreateCheckpointLatitude } from './createCheckpointLatitude';
import type { CreateCheckpointLongitude } from './createCheckpointLongitude';
import type { CreateCheckpointAddress } from './createCheckpointAddress';
import type { CreateCheckpointRequirements } from './createCheckpointRequirements';
import type { CreateCheckpointLanes } from './createCheckpointLanes';
import type { CreateCheckpointCheckpointDescription } from './createCheckpointCheckpointDescription';
import type { CreateCheckpointOrgDescription } from './createCheckpointOrgDescription';
import type { CreateCheckpointOrgLink } from './createCheckpointOrgLink';
import type { CreateCheckpointPhotoPermission } from './createCheckpointPhotoPermission';
import type { CreateCheckpointAccessible } from './createCheckpointAccessible';

export interface CreateCheckpoint {
  number?: CreateCheckpointNumber;
  area?: CreateCheckpointArea;
  org_name?: CreateCheckpointOrgName;
  org_abbreviation?: CreateCheckpointOrgAbbreviation;
  contact_person?: CreateCheckpointContactPerson;
  contact_email?: CreateCheckpointContactEmail;
  contact_phone?: CreateCheckpointContactPhone;
  category?: CreateCheckpointCategory;
  latitude?: CreateCheckpointLatitude;
  longitude?: CreateCheckpointLongitude;
  address?: CreateCheckpointAddress;
  requirements?: CreateCheckpointRequirements;
  lanes?: CreateCheckpointLanes;
  checkpoint_description?: CreateCheckpointCheckpointDescription;
  org_description?: CreateCheckpointOrgDescription;
  org_link?: CreateCheckpointOrgLink;
  photo_permission?: CreateCheckpointPhotoPermission;
  accessible?: CreateCheckpointAccessible;
}
