/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DBAdventureId } from './dBAdventureId';

export interface DBAdventure {
  name: string;
  year: number;
  ongoing?: boolean;
  test?: boolean;
  id?: DBAdventureId;
  active?: boolean;
}
