/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DeoverlapCheckpointsParams = {
step_meters?: number;
renumber_after?: boolean;
};
