/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImportErrorDetailError } from './importErrorDetailError';
import type { ImportErrorDetailRow } from './importErrorDetailRow';

export interface ImportErrorDetail {
  /** Type of error: lookup_error, update_error, validation_error, etc. */
  type: string;
  /** Error message or list of validation errors */
  error: ImportErrorDetailError;
  /** The row that caused the error */
  row: ImportErrorDetailRow;
}
