/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImportPayloadDataItem } from './importPayloadDataItem';

export interface ImportPayload {
  /** List of field names used to match existing records */
  identifiers: string[];
  /** Rows of checkpoint data keyed by output column name */
  data: ImportPayloadDataItem[];
}
