/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImportErrorDetail } from './importErrorDetail';

export interface ImportResult {
  message: string;
  /**
   * Number of records updated
   * @minimum 0
   */
  updated: number;
  /**
   * Number of records created
   * @minimum 0
   */
  created: number;
  errors?: ImportErrorDetail[];
  /** HTTP status code (e.g. 200, 207) */
  status: number;
}
