/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImportErrorDetailErrorAnyOfItem } from './importErrorDetailErrorAnyOfItem';

/**
 * Error message or list of validation errors
 */
export type ImportErrorDetailError = string | ImportErrorDetailErrorAnyOfItem[];
