/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PublicCheckpoint } from './publicCheckpoint';
import type { PublicTeam } from './publicTeam';
import type { PublicNews } from './publicNews';

export interface LinkedAdventure {
  name: string;
  year: number;
  ongoing: boolean;
  test: boolean;
  id: number;
  checkpoints: PublicCheckpoint[];
  teams: PublicTeam[];
  news: PublicNews[];
}
