/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModifyAppSettingsCurrentAdventureId } from './modifyAppSettingsCurrentAdventureId';

export interface ModifyAppSettings {
  current_adventure_id: ModifyAppSettingsCurrentAdventureId;
}
