/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModifyAdventureName } from './modifyAdventureName';
import type { ModifyAdventureYear } from './modifyAdventureYear';
import type { ModifyAdventureOngoing } from './modifyAdventureOngoing';
import type { ModifyAdventureTest } from './modifyAdventureTest';

export interface ModifyAdventure {
  name?: ModifyAdventureName;
  year?: ModifyAdventureYear;
  ongoing?: ModifyAdventureOngoing;
  test?: ModifyAdventureTest;
}
