/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModifyNewsTitleEn } from './modifyNewsTitleEn';
import type { ModifyNewsTitleFi } from './modifyNewsTitleFi';
import type { ModifyNewsTitleSv } from './modifyNewsTitleSv';
import type { ModifyNewsContentsEn } from './modifyNewsContentsEn';
import type { ModifyNewsContentsFi } from './modifyNewsContentsFi';
import type { ModifyNewsContentsSv } from './modifyNewsContentsSv';
import type { ModifyNewsActive } from './modifyNewsActive';

export interface ModifyNews {
  title_en?: ModifyNewsTitleEn;
  title_fi?: ModifyNewsTitleFi;
  title_sv?: ModifyNewsTitleSv;
  contents_en?: ModifyNewsContentsEn;
  contents_fi?: ModifyNewsContentsFi;
  contents_sv?: ModifyNewsContentsSv;
  active?: ModifyNewsActive;
}
