/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModifyScoreScore } from './modifyScoreScore';
import type { ModifyScorePlayers } from './modifyScorePlayers';
import type { ModifyScoreTeamId } from './modifyScoreTeamId';
import type { ModifyScoreCheckpointId } from './modifyScoreCheckpointId';

export interface ModifyScore {
  id: number;
  score?: ModifyScoreScore;
  players?: ModifyScorePlayers;
  team_id?: ModifyScoreTeamId;
  checkpoint_id?: ModifyScoreCheckpointId;
}
