/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PlayerPhone } from './playerPhone';

export interface Player {
  /** Name of the player */
  name: string;
  /** Phone number of the player */
  phone: PlayerPhone;
}
