/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PublicAdventure } from './publicAdventure';
import type { UnlinkedTeam } from './unlinkedTeam';
import type { PublicCheckpoint } from './publicCheckpoint';

export interface PublicScore {
  id: number;
  score: number;
  players: number;
  adventure: PublicAdventure;
  team: UnlinkedTeam;
  checkpoint: PublicCheckpoint;
  created_at: string;
}
