/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PublicNewsPublishedAt } from './publicNewsPublishedAt';

export interface PublicNews {
  title_en: string;
  title_fi: string;
  title_sv: string;
  contents_en: string;
  contents_fi: string;
  contents_sv: string;
  id: number;
  created_at: string;
  published_at: PublicNewsPublishedAt;
}
