/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface PublicCheckpoint {
  number: number;
  area: number;
  org_name: string;
  org_abbreviation: string;
  category: string;
  latitude: string;
  longitude: string;
  address: string;
  checkpoint_description: string;
  org_description: string;
  org_link: string;
  accessible: boolean;
  id: number;
}
