/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PublicTag } from './publicTag';

export interface PublicPhoto {
  key: string;
  views: number;
  likes: number;
  uploaded_at: string;
  id: number;
  original_url: string;
  resized_url: string;
  thumb_url: string;
  tags: PublicTag[];
}
