/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface PublicAdventure {
  name: string;
  year: number;
  ongoing: boolean;
  test: boolean;
  id: number;
}
