/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PublicAppSettingsCurrentAdventure } from './publicAppSettingsCurrentAdventure';

export interface PublicAppSettings {
  updated_at: string;
  current_adventure?: PublicAppSettingsCurrentAdventure;
}
