/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PublicAdventure } from './publicAdventure';

export interface PublicTeam {
  name: string;
  /** Unique identifier */
  id: number;
  adventure: PublicAdventure;
}
