/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type Role = typeof Role[keyof typeof Role];


 
export const Role = {
  guest: 'guest',
  user: 'user',
  admin: 'admin',
} as const;
