/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SortOption = typeof SortOption[keyof typeof SortOption];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortOption = {
  newest: 'newest',
  oldest: 'oldest',
  liked: 'liked',
  viewed: 'viewed',
} as const;
