/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TeamLeaderboardNumber } from './teamLeaderboardNumber';
import type { TeamLeaderboardLastScoreAt } from './teamLeaderboardLastScoreAt';

export interface TeamLeaderboard {
  name: string;
  id: number;
  number: TeamLeaderboardNumber;
  score: number;
  checkpoints: number;
  last_score_at: TeamLeaderboardLastScoreAt;
}
