/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateUserPassword } from './updateUserPassword';
import type { UpdateUserRole } from './updateUserRole';
import type { UpdateUserActive } from './updateUserActive';

export interface UpdateUser {
  username: string;
  email: string;
  password?: UpdateUserPassword;
  role?: UpdateUserRole;
  active?: UpdateUserActive;
}
